### ISSUE TITLE
Collision w/ 2-byte random suffixes

### ISSUE THREAD

**Issue by atz** [sul-dlss/terraform-module-aws-ecs#21]
This isn't really a lot of randomness:
```hcl
resource "random_id" "target_group_suffix" {
  byte_length = 2
}
...
  name  = "${var.service_name}-alb-tg-${random_id.target_group_suffix.hex}"
...
```

The tension here is between adding more bytes and keeping the composite multi-suffixed name under 32 chars.  It's already using 13 of those.  

Probably the best move is to keep the 4 characters, but use a bigger identifier-space than hexadecimal.

**Comment by jonrober** [comment]
I think this should be cleaned up entirely because it's an artifact of older code and I'm not exactly sure what it was meant to do.  The cluster creation does the same thing, and in both places it shouldn't be needed -- in the cluster you should be giving a unique cluster name, and here you should be giving a unique service name or other things would break.  Checking the AWS docs, the name only has to be unique per account/region, not just region like S3.  

So the random bytes aren't actually useful, and just taking up some of those characters.  The only time when they might be useful is if someone outside of the module was creating security groups and happened to use the same "service-alb-tg", but at that point it can happen regardless just by two people outside of the module conflicting with each other.  So the module isn't gaining anything by this.

Though I should look at the existing service names and see what we're using and if it makes sense to combo it with cluster name as well or not, if maybe it would be cleaner and safer to use both.  That runs into the name size limit though.

**Comment by jonrober** [comment]
Removed the random_id from the target group in newer versions of module.
